
export interface Question {
    id: number;
    pillar: 'within' | 'out' | 'up' | 'beyond';
    comp: string;
    text: string;
    scale: 'freq' | 'agree';
}

export const DB: Question[] = [
    // --- PILLAR 1: WITHIN ---
    { id: 1, pillar: 'within', comp: 'Autoeficacia y Seguridad', text: "Cuando enfrento un desafío difícil en el trabajo, confío en mis capacidades para resolverlo sin mostrar arrogancia.", scale: 'freq' },
    { id: 2, pillar: 'within', comp: 'Autoeficacia y Seguridad', text: "Si me comprometo con mi equipo a hacer algo, cumplo esa promesa con acciones coherentes.", scale: 'freq' },
    { id: 3, pillar: 'within', comp: 'Gestión de Creencias', text: "Reflexiono de forma activa sobre mis propias creencias limitantes y trabajo para reemplazarlas por una mentalidad de crecimiento.", scale: 'freq' },
    { id: 4, pillar: 'within', comp: 'Gestión de Creencias', text: "Cuando enfrento un contratiempo, en lugar de preguntarme '¿Por qué a mí?', me pregunto '¿Qué puedo aprender?'.", scale: 'freq' },
    { id: 5, pillar: 'within', comp: 'Accountability', text: "Ante un problema, evito poner excusas y tomo las decisiones necesarias, reconociendo que tengo el control.", scale: 'agree' },
    { id: 6, pillar: 'within', comp: 'Accountability', text: "Cuando algo sale mal por mi responsabilidad, no culpo a factores externos; asumo mi error y busco solución.", scale: 'freq' },
    { id: 7, pillar: 'within', comp: 'Autoconciencia Emocional', text: "Soy consciente de mis emociones en tiempo real y reconozco cómo pueden influir en mis reacciones.", scale: 'agree' },
    { id: 8, pillar: 'within', comp: 'Autoconciencia Emocional', text: "Tengo identificadas las situaciones que disparan emociones negativas en mí, lo cual me ayuda a gestionarlas.", scale: 'agree' },
    { id: 9, pillar: 'within', comp: 'Regulación Emocional', text: "Cuando estoy bajo una presión intensa en el trabajo, logro mantener la calma y no reaccionar de forma impulsiva.", scale: 'freq' },
    { id: 10, pillar: 'within', comp: 'Regulación Emocional', text: "Si siento frustración con el equipo, la expreso de manera controlada y asertiva, sin perder la compostura.", scale: 'freq' },
    { id: 11, pillar: 'within', comp: 'Regulación Emocional', text: "Después de una situación tensa, soy capaz de recuperarme con rapidez usando técnicas de autorregulación.", scale: 'freq' },
    { id: 12, pillar: 'within', comp: 'Gestión de Energía', text: "Me aseguro de descansar y desconectar para mantener mi mente clara, sabiendo que el agotamiento perjudica mi liderazgo.", scale: 'freq' },
    { id: 13, pillar: 'within', comp: 'Gestión de Energía', text: "Tengo rutinas de bienestar (ejercicio, meditación) integradas en mi semana para recargar energías.", scale: 'freq' },
    { id: 14, pillar: 'within', comp: 'Claridad de Propósito', text: "Tengo claramente definido mi 'para qué' como líder y sé articular cómo mi trabajo contribuye a un propósito más grande.", scale: 'agree' },
    { id: 15, pillar: 'within', comp: 'Claridad de Propósito', text: "Cuando enfrento una decisión difícil, la tomo considerando si está alineada con mis valores y propósito.", scale: 'freq' },
    { id: 16, pillar: 'within', comp: 'Integridad', text: "Aunque esté bajo presión, me niego a violar mis valores o comprometer mi ética.", scale: 'agree' },
    { id: 17, pillar: 'within', comp: 'Integridad', text: "Soy transparente con mi equipo: si cometo un error lo admito abiertamente.", scale: 'freq' },
    { id: 18, pillar: 'within', comp: 'Autenticidad', text: "En mi rol de líder me presento tal como soy, sin adoptar una 'máscara' corporativa.", scale: 'agree' },
    { id: 19, pillar: 'within', comp: 'Práctica Reflexiva', text: "Suelo dedicar tiempo a reflexionar sobre mis experiencias (journaling, retrospección) para aprender de ellas.", scale: 'freq' },
    { id: 20, pillar: 'within', comp: 'Práctica Reflexiva', text: "Después de un proyecto, analizo con honestidad qué podría haber hecho mejor.", scale: 'freq' },
    { id: 21, pillar: 'within', comp: 'Feedback', text: "Periódicamente le pido a colegas o miembros de mi equipo feedback sincero sobre mi desempeño.", scale: 'freq' },
    { id: 22, pillar: 'within', comp: 'Feedback', text: "Cuando alguien me hace una crítica, la recibo sin ponerme a la defensiva y agradezco los comentarios.", scale: 'freq' },
    { id: 23, pillar: 'within', comp: 'Mentalidad de Crecimiento', text: "Cuando enfrento un desafío, lo percibo como una oportunidad de aprendizaje en vez de un fracaso.", scale: 'agree' },
    { id: 24, pillar: 'within', comp: 'Mentalidad de Crecimiento', text: "Estoy dispuesto a salir de mi zona de confort para desarrollar habilidades nuevas.", scale: 'agree' },
    { id: 25, pillar: 'within', comp: 'Regulación Somática', text: "Cuido mi sueño, alimentación y ejercicio para manejar el estrés y asegurar un desempeño óptimo.", scale: 'freq' },
    { id: 26, pillar: 'within', comp: 'Regulación Somática', text: "Soy consciente de las señales físicas de estrés en mí y tomo medidas oportunas.", scale: 'freq' },
    { id: 27, pillar: 'within', comp: 'Compostura', text: "Ante una crisis, consigo mantener la serenidad y el profesionalismo.", scale: 'freq' },
    { id: 28, pillar: 'within', comp: 'Compostura', text: "Incluso en una discusión acalorada, controlo mi tono de voz y lenguaje corporal.", scale: 'freq' },
    { id: 29, pillar: 'within', comp: 'Re-alineación Cognitiva', text: "Si una situación adversa me abruma, trato de replantearla mentalmente de forma constructiva.", scale: 'freq' },
    { id: 30, pillar: 'within', comp: 'Re-alineación Cognitiva', text: "Cuando detecto un pensamiento negativo recurrente, deliberadamente lo sustituyo por una perspectiva realista.", scale: 'freq' },

    // --- PILLAR 2: SHINE OUT (Items 31-46) ---
    { id: 31, pillar: 'out', comp: 'Claridad e Inspiración', text: "Cuando comunico objetivos, lo hago de forma clara, explicando qué espero y por qué es importante.", scale: 'freq' },
    { id: 32, pillar: 'out', comp: 'Claridad e Inspiración', text: "Al compartir la visión, uso un tono entusiasta e historias que inspiren al equipo.", scale: 'freq' },
    { id: 33, pillar: 'out', comp: 'Escucha Activa', text: "En reuniones, dejo que cada quien se exprese sin interrumpir y escucho atentamente.", scale: 'freq' },
    { id: 34, pillar: 'out', comp: 'Escucha Activa', text: "Cuando un colaborador expresa una preocupación, reconozco sus sentimientos y su perspectiva.", scale: 'freq' },
    { id: 35, pillar: 'out', comp: 'Adaptabilidad Comunicativa', text: "Adapto mi forma de comunicarme según la audiencia (evito jerga con no expertos).", scale: 'freq' },
    { id: 36, pillar: 'out', comp: 'Adaptabilidad Comunicativa', text: "Estoy atento al lenguaje corporal del interlocutor y ajusto mi mensaje para ser comprendido.", scale: 'freq' },
    { id: 37, pillar: 'out', comp: 'Construcción de Confianza', text: "Si prometo algo a mi equipo, cumplo con ese compromiso de forma consistente.", scale: 'freq' },
    { id: 38, pillar: 'out', comp: 'Construcción de Confianza', text: "Cuando alguien me comparte información confidencial, la mantengo reservada y con respeto.", scale: 'freq' },
    { id: 39, pillar: 'out', comp: 'Influencia Ética', text: "Respaldo mis propuestas con datos y hechos concretos en vez de apoyarme en mi autoridad.", scale: 'freq' },
    { id: 40, pillar: 'out', comp: 'Influencia Ética', text: "Influyo en mi equipo apelando a valores ideales compartidos para motivar colaboración.", scale: 'freq' },
    { id: 41, pillar: 'out', comp: 'Reconocimiento', text: "Cuando un miembro del equipo logra algo, reconozco su logro de forma específica y oportuna.", scale: 'freq' },
    { id: 42, pillar: 'out', comp: 'Feedback Constructivo', text: "Al dar feedback, me enfoco en la conducta específica y ofrezco sugerencias de mejora.", scale: 'freq' },
    { id: 43, pillar: 'out', comp: 'Influencia Virtual', text: "Soy capaz de motivar a mi equipo a distancia, aprovechando herramientas digitales.", scale: 'freq' },
    { id: 44, pillar: 'out', comp: 'Influencia Virtual', text: "En equipos remotos, me comunico proactivamente para mantener mi presencia.", scale: 'freq' },
    { id: 45, pillar: 'out', comp: 'Ingeniería del Lenguaje', text: "Cuando necesito algo, formulo un pedido claro especificando qué requiero y para cuándo.", scale: 'freq' },
    { id: 46, pillar: 'out', comp: 'Ingeniería del Lenguaje', text: "Si veo que no podré cumplir un compromiso, lo comunico y renegocio con antelación.", scale: 'freq' },

    // --- PILLAR 3: SHINE UP (Items 47-72) ---
    { id: 47, pillar: 'up', comp: 'Conectividad', text: "Promuevo que mi equipo colabore con otras áreas, conectándolos activamente.", scale: 'freq' },
    { id: 48, pillar: 'up', comp: 'Conectividad', text: "Me involucro en eventos de la industria y mantengo relaciones con clientes clave.", scale: 'freq' },
    { id: 49, pillar: 'up', comp: 'Gestión de Relaciones', text: "Cultivo relaciones sólidas con personas clave de la organización para construir alianzas.", scale: 'freq' },
    { id: 50, pillar: 'up', comp: 'Gestión de Relaciones', text: "Me intereso genuinamente por las personas de mi equipo (no solo resultados).", scale: 'freq' },
    { id: 51, pillar: 'up', comp: 'Visibilidad Estratégica', text: "Doy visibilidad a los logros de mi equipo presentándolos en reuniones ejecutivas.", scale: 'freq' },
    { id: 52, pillar: 'up', comp: 'Visibilidad Estratégica', text: "He desarrollado una reputación clara como líder y comunico esa marca personal.", scale: 'agree' },
    { id: 53, pillar: 'up', comp: 'Pensamiento Estratégico', text: "Regularmente analizo tendencias de la industria para anticipar cambios estratégicos.", scale: 'freq' },
    { id: 54, pillar: 'up', comp: 'Pensamiento Estratégico', text: "En la toma de decisiones, priorizo el largo plazo sobre necesidades inmediatas.", scale: 'freq' },
    { id: 55, pillar: 'up', comp: 'Visión Compartida', text: "Trabajo con mi equipo para construir una visión de futuro motivadora.", scale: 'freq' },
    { id: 56, pillar: 'up', comp: 'Visión Compartida', text: "Comunico la visión de la organización y la vinculo con las tareas cotidianas.", scale: 'freq' },
    { id: 57, pillar: 'up', comp: 'Alineación de Metas', text: "Convierto la visión estratégica en objetivos concretos y medibles para mi equipo.", scale: 'freq' },
    { id: 58, pillar: 'up', comp: 'Alineación de Metas', text: "Realizo seguimientos frecuentes y ajusto planes si detecto desvíos importantes.", scale: 'freq' },
    { id: 59, pillar: 'up', comp: 'Decisión bajo Incertidumbre', text: "Cuando debo decidir con información incompleta, lo hago con criterio y confianza.", scale: 'agree' },
    { id: 60, pillar: 'up', comp: 'Decisión bajo Incertidumbre', text: "Si enfrento una decisión arriesgada, evalúo pros y contras y tomo acción calculada.", scale: 'freq' },
    { id: 61, pillar: 'up', comp: 'Resolución Causa Raíz', text: "Investigo a fondo con datos para encontrar la causa raíz de problemas recurrentes.", scale: 'freq' },
    { id: 62, pillar: 'up', comp: 'Resolución Causa Raíz', text: "Involucro a las personas pertinentes para analizar problemas complejos antes de decidir.", scale: 'freq' },
    { id: 63, pillar: 'up', comp: 'Agilidad', text: "Si las condiciones cambian, adapto los planes ágilmente sin aferrarme al original.", scale: 'freq' },
    { id: 64, pillar: 'up', comp: 'Agilidad', text: "Animo a mi equipo a cambiar de rumbo cuando las circunstancias lo requieren.", scale: 'freq' },
    { id: 65, pillar: 'up', comp: 'Estimulación Intelectual', text: "Hago preguntas desafiantes que impulsen al equipo a pensar fuera de lo convencional.", scale: 'freq' },
    { id: 66, pillar: 'up', comp: 'Estimulación Intelectual', text: "Doy espacio y recursos para experimentar, tolerando errores inteligentes.", scale: 'freq' },
    { id: 67, pillar: 'up', comp: 'Gestión del Error', text: "Cuando ocurre un error, lo analizo con el equipo para extraer lecciones, no culpables.", scale: 'freq' },
    { id: 68, pillar: 'up', comp: 'Gestión del Error', text: "Si alguien comete un error, reacciono con calma y lo tomo como oportunidad de coaching.", scale: 'freq' },
    { id: 69, pillar: 'up', comp: 'Lectura de Poder', text: "Soy consciente de quiénes tienen influencia en la organización para impulsar iniciativas.", scale: 'agree' },
    { id: 70, pillar: 'up', comp: 'Lectura de Poder', text: "Construyo redes de apoyo para las iniciativas de mi equipo de forma ética.", scale: 'agree' },
    { id: 71, pillar: 'up', comp: 'Liderazgo Industria 5.0', text: "Me mantengo actualizado sobre tendencias tecnológicas (IA, automatización) relevantes.", scale: 'freq' },
    { id: 72, pillar: 'up', comp: 'Liderazgo Industria 5.0', text: "Busco adaptar las prácticas de mi equipo integrando nuevas tecnologías.", scale: 'freq' },

    // --- PILLAR 4: SHINE BEYOND (Items 73-96) ---
    { id: 73, pillar: 'beyond', comp: 'Mentoría y Sucesión', text: "Identifico a personas con alto potencial y dedico tiempo a mentorarlas para la sucesión.", scale: 'freq' },
    { id: 74, pillar: 'beyond', comp: 'Mentoría y Sucesión', text: "Comparto mis conocimientos con líderes emergentes para acelerar su desarrollo.", scale: 'freq' },
    { id: 75, pillar: 'beyond', comp: 'Empowerment', text: "Delego responsabilidades desafiantes y doy autonomía para decidir cómo hacerlas.", scale: 'freq' },
    { id: 76, pillar: 'beyond', comp: 'Empowerment', text: "Aclaro el qué, pero permito al equipo decidir el cómo, evitando el micro-management.", scale: 'freq' },
    { id: 77, pillar: 'beyond', comp: 'Desafío para Crecimiento', text: "Desafío a mi equipo con objetivos ambiciosos que los hagan crecer.", scale: 'freq' },
    { id: 78, pillar: 'beyond', comp: 'Desafío para Crecimiento', text: "Si imponen retos desmedidos al equipo, intervengo para equilibrar la carga.", scale: 'freq' },
    { id: 79, pillar: 'beyond', comp: 'Ética Social', text: "Incorporo consideraciones éticas y de impacto social en decisiones estratégicas.", scale: 'freq' },
    { id: 80, pillar: 'beyond', comp: 'Ética Social', text: "Promuevo iniciativas que generan valor social y modelo integridad en su ejecución.", scale: 'freq' },
    { id: 81, pillar: 'beyond', comp: 'Liderazgo de Servicio', text: "Priorizo el bienestar de mi equipo y la organización por encima de mi interés personal.", scale: 'agree' },
    { id: 82, pillar: 'beyond', comp: 'Liderazgo de Servicio', text: "Estoy dispuesto a hacer sacrificios personales si beneficio al equipo u organización.", scale: 'agree' },
    { id: 83, pillar: 'beyond', comp: 'Inclusión y Equidad', text: "Me aseguro de crear un ambiente inclusivo donde se valoran perspectivas diversas.", scale: 'freq' },
    { id: 84, pillar: 'beyond', comp: 'Inclusión y Equidad', text: "Actúo para corregir sesgos en decisiones de contratación o evaluación.", scale: 'freq' },
    { id: 85, pillar: 'beyond', comp: 'Cultura Organizacional', text: "Promuevo los valores de la cultura organizacional y soy un ejemplo viviente de ellos.", scale: 'freq' },
    { id: 86, pillar: 'beyond', comp: 'Cultura Organizacional', text: "He implementado prácticas recurrentes que refuerzan la cultura organizacional.", scale: 'freq' },
    { id: 87, pillar: 'beyond', comp: 'Humildad', text: "Cuando hay éxito, dejo que el equipo brille; cuando hay fracaso, asumo la responsabilidad.", scale: 'freq' },
    { id: 88, pillar: 'beyond', comp: 'Humildad', text: "Admito cuando no tengo todas las respuestas y busco consejo sin ego.", scale: 'freq' },
    { id: 89, pillar: 'beyond', comp: 'Propósito (Meaning)', text: "Ayudo a mi equipo a ver cómo su trabajo conecta con un propósito mayor.", scale: 'freq' },
    { id: 90, pillar: 'beyond', comp: 'Propósito (Meaning)', text: "Comparto historias que muestran el impacto positivo de nuestro trabajo en otros.", scale: 'freq' },
    { id: 91, pillar: 'beyond', comp: 'Diversidad Cognitiva', text: "Asigno tareas aprovechando las fortalezas diversas (analíticos, creativos) del equipo.", scale: 'freq' },
    { id: 92, pillar: 'beyond', comp: 'Diversidad Cognitiva', text: "Fomento debates saludables donde las opiniones divergentes sean bienvenidas.", scale: 'freq' },
    { id: 93, pillar: 'beyond', comp: 'Conciencia Sistémica', text: "Considero cómo mis decisiones afectan al conjunto de la organización o comunidad.", scale: 'freq' },
    { id: 94, pillar: 'beyond', comp: 'Conciencia Sistémica', text: "Participo en iniciativas de responsabilidad social para contribuir más allá del negocio.", scale: 'freq' },
    { id: 95, pillar: 'beyond', comp: 'Legado', text: "Pienso en cómo quiero ser recordado y oriento mis acciones a dejar una huella positiva.", scale: 'agree' },
    { id: 96, pillar: 'beyond', comp: 'Legado', text: "Dedico tiempo a actividades que trascienden mi rol inmediato (mentorías, docencia).", scale: 'freq' }
];

export const SCALES = {
    freq: ["Nunca", "Rara vez", "A veces", "A menudo", "Siempre"],
    agree: ["Totalmente en desacuerdo", "En desacuerdo", "Neutral", "De acuerdo", "Totalmente de acuerdo"]
};

export const PILLAR_INFO = {
    within: { title: "Shine Within", sub: "Esencia y Autoliderazgo" },
    out: { title: "Shine Out", sub: "Presencia e Influencia" },
    up: { title: "Shine Up", sub: "Ecosistema y Estrategia" },
    beyond: { title: "Shine Beyond", sub: "Legado y Trascendencia" }
};

export const COMP_DEFINITIONS: Record<string, string> = {
    'Autoeficacia y Seguridad': 'Confianza en la propia capacidad para lograr metas y manejar desafíos.',
    'Gestión de Creencias': 'Capacidad para identificar y transformar pensamientos limitantes.',
    'Accountability': 'Asumir plena responsabilidad por los resultados, sin excusas.',
    'Autoconciencia Emocional': 'Reconocimiento en tiempo real de las propias emociones y su impacto.',
    'Regulación Emocional': 'Habilidad para gestionar respuestas emocionales bajo presión.',
    'Gestión de Energía': 'Administración estratégica de los recursos físicos y mentales.',
    'Claridad de Propósito': 'Conexión profunda con el "para qué" personal y profesional.',
    'Integridad': 'Coherencia inquebrantable entre valores, palabras y acciones.',
    'Autenticidad': 'Liderar desde la propia esencia, sin máscaras.',
    'Práctica Reflexiva': 'Hábito de analizar experiencias para extraer aprendizaje continuo.',
    'Feedback': 'Búsqueda y aceptación proactiva de retroalimentación.',
    'Mentalidad de Crecimiento': 'Ver los retos como oportunidades de desarrollo.',
    'Regulación Somática': 'Conexión cuerpo-mente para el manejo del estrés.',
    'Compostura': 'Mantener la serenidad y claridad en momentos críticos.',
    'Re-alineación Cognitiva': 'Capacidad de reinterpretar situaciones adversas de forma constructiva.',
    'Claridad e Inspiración': 'Comunicar la visión de forma que movilice a otros.',
    'Escucha Activa': 'Escuchar para comprender, no solo para responder.',
    'Adaptabilidad Comunicativa': 'Ajustar el estilo de comunicación a la audiencia.',
    'Construcción de Confianza': 'Crear vínculos basados en la fiabilidad y cercanía.',
    'Influencia Ética': 'Persuadir basándose en valores y beneficios mutuos.',
    'Reconocimiento': 'Valorar visiblemente el aporte de los demás.',
    'Feedback Constructivo': 'Dar retroalimentación que ayuda a crecer, no solo a corregir.',
    'Influencia Virtual': 'Liderar efectivamente a través de canales digitales.',
    'Ingeniería del Lenguaje': 'Uso preciso del lenguaje para coordinar acciones.',
    'Conectividad': 'Crear puentes entre personas y áreas diversas.',
    'Gestión de Relaciones': 'Cultivar redes de contacto estratégicas y genuinas.',
    'Visibilidad Estratégica': 'Posicionar al equipo y sus logros en la organización.',
    'Pensamiento Estratégico': 'Anticipar tendencias y planificar a largo plazo.',
    'Visión Compartida': 'Co-crear un futuro deseable con el equipo.',
    'Alineación de Metas': 'Conectar objetivos individuales con la estrategia macro.',
    'Decisión bajo Incertidumbre': 'Actuar con determinación aun sin tener toda la información.',
    'Resolución Causa Raíz': 'Ir al fondo de los problemas en lugar de tratar síntomas.',
    'Agilidad': 'Adaptarse rápidamente a cambios del entorno.',
    'Estimulación Intelectual': 'Desafiar al equipo a pensar de formas nuevas.',
    'Gestión del Error': 'Tratar el error como fuente de aprendizaje, no de castigo.',
    'Lectura de Poder': 'Entender las dinámicas políticas de la organización.',
    'Liderazgo Industria 5.0': 'Integrar tecnología y humanidad en la gestión.',
    'Mentoría y Sucesión': 'Preparar a la próxima generación de líderes.',
    'Empowerment': 'Otorga poder y autonomía real al equipo.',
    'Desafío para Crecimiento': 'Impulsar al equipo a superar sus propios límites.',
    'Ética Social': 'Considerar el impacto social en las decisiones de negocio.',
    'Liderazgo de Servicio': 'Priorizar las necesidades del equipo sobre las propias.',
    'Inclusión y Equidad': 'Crear entornos donde todos se sientan valorados.',
    'Cultura Organizacional': 'Ser guardián y modelo de los valores culturales.',
    'Humildad': 'Reconocer limitaciones y valorar el aporte de otros.',
    'Propósito (Meaning)': 'Ayudar a otros a encontrar sentido en su trabajo.',
    'Diversidad Cognitiva': 'Valorar y aprovechar diferentes formas de pensar.',
    'Conciencia Sistémica': 'Entender la organización como un todo interconectado.',
    'Legado': 'Construir algo que perdure más allá de la propia gestión.'
};
