'use client'

import React from 'react'
import TaxonomyDiamondGraph from '@/components/TaxonomyDiamondGraph'

type TaxonomyItem = {
    id: string
    name: string
    type: string
    active: boolean
    children?: TaxonomyItem[]
}

type ContentItem = {
    id: string
    title: string
    primaryPillar: string
    sub?: string | null
    competence?: string | null
    behavior?: string | null
}

type Props = {
    taxonomy: TaxonomyItem[]
    inventory: ContentItem[]
    focus: 'ALL' | 'Shine Within' | 'Shine Out' | 'Shine Up' | 'Shine Beyond'
}

export default function PublicDiamondView({ taxonomy, inventory, focus }: Props) {
    return (
        <div className="flex flex-col h-screen w-screen bg-white">
            <header className="px-8 py-6 flex justify-between items-center border-b border-gray-100 z-10 bg-white">
                <div>
                    <h1 className="text-2xl font-black text-slate-900 tracking-tighter flex items-center gap-3">
                        ARQUITECTURA 4SHINE®
                        <span className="text-xs bg-accent/10 text-accent px-2 py-1 rounded-full font-bold uppercase tracking-widest">
                            {focus === 'ALL' ? 'General' : focus}
                        </span>
                    </h1>
                    <p className="text-xs text-slate-400 font-medium uppercase tracking-widest mt-1">
                        Visualización Estructural del Framework de Escalamiento
                    </p>
                </div>
                <div className="flex items-center gap-4">
                    <div className="hidden md:flex flex-col items-end">
                        <span className="text-[10px] font-black text-slate-300 uppercase tracking-[0.2em]">System Status</span>
                        <span className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">Live Metadata Sync</span>
                    </div>
                    <div className="w-10 h-10 bg-slate-50 border border-slate-100 rounded-xl flex items-center justify-center">
                        <img src="/favicon.ico" alt="logo" className="w-6 h-6 grayscale opacity-50" />
                    </div>
                </div>
            </header>

            <main className="flex-1 relative overflow-hidden bg-slate-50">
                <TaxonomyDiamondGraph
                    data={taxonomy}
                    focus={focus}
                    inventory={inventory}
                    showGaps={false}
                />

                {/* Legend Overlay */}
                <div className="absolute bottom-6 left-6 bg-white/80 backdrop-blur-md border border-gray-100 p-4 rounded-2xl shadow-xl z-10 max-w-xs transition-all hover:bg-white pointer-events-none md:pointer-events-auto">
                    <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] mb-3">Leyenda del Sistema</h4>
                    <div className="space-y-2">
                        <LegendItem color="#10b981" label="Shine Up" sub="Ecosistema Relacional" />
                        <LegendItem color="#8b5cf6" label="Shine Within" sub="Esencia" />
                        <LegendItem color="#3b82f6" label="Shine Out" sub="Presencia Estratégica" />
                        <LegendItem color="#f59e0b" label="Shine Beyond" sub="Legado" />
                    </div>
                    <div className="mt-4 pt-3 border-t border-gray-100">
                        <p className="text-[9px] text-slate-400 leading-relaxed italic">
                            Esta visualización representa la interconexión de pilares, competencias y conductas clave del sistema 4Shine®.
                        </p>
                    </div>
                </div>

                <div className="absolute bottom-6 right-6 hidden md:block">
                    <p className="text-[10px] font-bold text-slate-300 uppercase tracking-[0.3em] rotate-90 origin-right translate-y-[-100%]">
                        Property of 4Shine Pro
                    </p>
                </div>
            </main>

            <footer className="px-8 py-3 bg-white border-t border-gray-100 flex justify-between items-center text-[9px] font-black text-slate-300 uppercase tracking-[0.2em]">
                <span>Generated by 4Shine AI Strategy System</span>
                <span>© 2026 4Shine • Todos los derechos reservados</span>
            </footer>
        </div>
    )
}

function LegendItem({ color, label, sub }: { color: string, label: string, sub: string }) {
    return (
        <div className="flex items-center gap-3">
            <div className="w-3 h-3 rounded-sm rotate-45" style={{ backgroundColor: color }} />
            <div>
                <div className="text-[11px] font-black text-slate-800 leading-none">{label}</div>
                <div className="text-[9px] text-slate-400 mt-0.5">{sub}</div>
            </div>
        </div>
    )
}
